__tests__/index.js, index.js
Currently, if `.github/config.yml` is missing (or doesn't have the `todo` key, everything borks.
=> Work even if config file is missing

LICENSE
Fix up your LICENSE you doofus.
=> Fix up LICENSE

__tests__/fixtures/payloads.js, __tests__/index.js, __tests__/lib/generate-body.js, index.js
Fix an error when merging PRs or receiving push payloads with no `head_commit` would throw an error.
Fixes #25
=> Fix author error

__tests__/fixtures/bodies/caseinsensitive.txt, __tests__/fixtures/files/at-end.js, __tests__/lib/generate-blob-link.js, lib/generate-blob-link.js
Adds tests and functionality to produce a correct blob link if the issue-to-be is at the end of a file, or if the star to the blob + the blobLines config is past the last line of the file.
Closes #39
=> Fix blob links

docs/deploy.md
Add docs explaining deployment and permissions.
=> Add deploy docs

LICENSE
Didn't realize I put the repo URL in the license file 🤦‍♂️
=> Replace repo url in license file

lib/generate-blob-link.js
Improve the process of obtaining number of lines to create a blob link.
=> Improve blob link

.gitignore, env.yml.example, package-lock.json, package.json, serverless.yml
=> Use serverless npm scripts

__tests__/fixtures/payloads.js, __tests__/index.js, __tests__/lib/reopen-closed.js, lib/organize-commits.js
=> Ignore config yml

__tests__/helpers.js, __tests__/index.js, __tests__/languages.js, __tests__/shimRAF.js, index.js, package.json
Write a whole bunch of in-depth tests to make sure that duplicate issues aren't being generated.
=> Fix duplicate issues

__tests__/fixtures/payloads.js, __tests__/helpers.js, __tests__/open-issues.js, lib/open-issues.js, package-lock.json, package.json
Rather than comparing sha hashes, this PR changes the check for merge push to identify based on the commits parents. If it has multiple parents, it's a merge commit.
Closes #69
=> Fix merge pushes

README.md
=> Fix badge alignment

README.md
=> Add uptimerobot badge

.travis.yml, index.js, package.json, src/push-handler.js, src/utils/chunk-diff.js, src/utils/handler-setup.js, tests/helpers.js, tests/issue-rename-handler.test.js, tests/pull-request-handler.test.js, tests/pull-request-merge-handler.test.js, tests/push-handler.test.js
Update to [Probot 7.0.0](https://github.com/probot/probot/releases/tag/v7.0.0) and ensure that other dependencies are up to date. Also removes the Travis test for Node 9 and replaces it with Node 10.
=> Probot Seven

.gitignore, package-lock.json, package.json, src/index.js, src/utils/chunk-diff.js, tests/issue-rename-handler.test.js, tests/pull-request-handler.test.js, tests/pull-request-merge-handler.test.js, tests/push-handler.test.js
Bumps a few dependencies, namely Probot - this is specifically to tackle a deprecated API endpoint, that a new version of Probot covers. I've also gone and fixed CI.
=> Bump some dependencies

lib/pull-request-handler.js, lib/pull-request-merged-handler.js, lib/push-handler.js, lib/utils/avoid-replication-lag.js, package-lock.json, package.json, tests/helpers.js
This PR adds a `before` hook to all `GET` requests, to basically say "before you request that info, wait a full second." This prevents the app from reacting to webhooks so quickly that the expected API resources haven't fully replicated to the many GitHub data stores.
=> Replication lag

package-lock.json, package.json
Updates some dependencies and runs `npm audit fix` to patch some security vulnerabilities.
=> Upgrade dependencies and run npm audit fix

bin/todo.js
This PR makes a couple of updates to the CLI. The main updates are around methods on the Octokit client - a few methods were deprecated prior to #196. I've also done a little cleanup to be more "DRY" with some objects. And lastly, I've used Probot's internal "beefed-up" Octokit client instead of the regular one, just for the sake of consistency.
=> Updates to the CLI

lib/utils/get-diff.js
=> Increased max diff limit from 100000 to 150000

lib/utils/main-loop.js, tests/fixtures/diffs/middle-of-sentence.txt, tests/lib/main-loop.test.js
=> Add boundary check of title keyword
