__tests__/lib/commit-is-in-pr.js
__tests__/lib/generate-blob-link.js
__tests__/lib/generate-body.js
__tests__/lib/ssr-template.js

Thanks to @matchai being aggressive when trying to fix problems unrelated to the ones he was asked to fix, this PR removes redundant `typeof` assertions.

Remove redundant assertions

---

package-lock.json
package.json

Because I'm committing to the bundled React front-end files (which I do to prevent unneeded server load), there are a couple dependencies that are only needed in dev environments.

Move front-end deps to dev-deps

---

__tests__/fixtures/payloads.js
__tests__/index.js
index.js

Adds an `'installation'` event handler to log newly installed repos to the console.
Closes #26.

Installation event

---

package-lock.json
package.json

Using the `probot/probot` dependency is a little risky, in case there are breaking changes made to the repo but not published to NPM. This PR edits the deps list to use Probot from the npm registry.

Use NPM version of Probot instead of the GitHub repo

---

README.md
__tests__/fixtures/bodies/reopen.txt
__tests__/fixtures/configs/reopenClosedFalse.yml
__tests__/index.js
__tests__/lib/reopen-closed.js
index.js
lib/default-config.js
lib/reopen-closed.js

This PR adds functionality to reopen closed issues if the same todo is found in a newly pushed file. It comes with a `reopenClosed` config, whose default is `true`.
Closes #33.

Reopen closed issues

---

README.md

Looks like the Travis badge is showing the status of the last build on this repo, rather than just master branch builds! 😳

Update Travis badge to only show the status of master branch builds

---

lib/check-for-duplicate-issue.js
lib/open-issues.js

There have been too many cases of duplicate issues being created because a `TODO` has been moved from one file to another. This PR removes the file check, so that won't happen any more.

Remove file key check

---

lib/search-contents-for-titles.js

Many people will start their todo comments with `KEYWORD:` (note the `:` character). Unfortunately, people usually don't include that in the keywords in the config file (and/or the default is skewed against it), so I've added a check for the `:` character in the RegEx for title parsing.

Tweak RegEx to add colon

---

README.md
bin/todo.js
src/pull-request-handler.js
src/pull-request-merged-handler.js
src/push-handler.js
src/utils/chunk-diff.js
src/utils/handler-setup.js

Reworks the diff parsing to parse chunks at a time, rather than the whole diff string at once. This is mainly because of a limitation I got to with the RegEx; I wasn't able to stop it from including chunks that were earlier in the diff in matched chunks (that contain `todo`s). That bug (first spotted in #111) made code blobs report the wrong file and line number.
I'd love to find a way to make that RegEx work to avoid more loops, but this is good enough for now.
While getting this to work, I also added a `-f, --file` option to the CLI to run a file through the parser. Handy for testing out user-submitted diffs!
Closes #111

Parse diff chunks at a time

---

index.js
src/pull-request-handler.js
src/pull-request-merged-handler.js
src/push-handler.js
src/utils/parse-chunk.js

Rename `parse-diff` to `parse-chunk` (because that's what its doing now), and fix the missing `id` property on the context object in the logs.

Tweak chunk parser

---

package.json

Reverts JasonEtco/todo#118 - when I tried to deploy, GCF reported an error because of an `async/await` in Bottleneck:
https://github.com/SGrondin/bottleneck/commit/02db071cb63071db597e1063c68c2fcd4c16d77d

Revert "Update probot-ts to the latest version 🚀"

---

bin/todo.js
package.json

Update the CLI to use `@octokit/rest` instead of `github`, since the latter is now deprecated. Thanks to @gr2m for spotting it, and for everything he does for the Node Octokit library ❤️

Update to octokit rest

---

lib/pull-request-merged-handler.js
tests/pull-request-merge-handler.test.js

This PR adds a small check to the `pull-request-merged-handler`, to ensure that its not doing anything on PRs that have been closed without merging.
Closes #167

Don't act on closed, unmerged PRs

---

lib/utils/check-for-body.js
package-lock.json
package.json
tests/lib/check-for-body.test.js

In the refactor #165, I inadvertandly removed support for the `:` character when parsing for body keywords. So, this would work:
```diff
+ // BODY Hey!
```
But this would not:
```diff
+ // BODY: Nope!
```
This also pointed out some missing tests so I went ahead and added those.
Fixes #171

Allows : characters in BODY keyword retrieval

---

index.js
lib/ignore-repos.js
lib/utils/main-loop.js
lib/utils/should-exclude-file.js
tests/lib/ignore-repos.test.js
tests/lib/should-exclude-file.test.js

I've been noticing some massive spikes in memory usage at seemingly random times, and I think I've narrowed it down to a couple repos committing massive diffs via automation. This PR adds a couple of guards against intentional or unintentional "bad actors" that impact performance of the app:
* Added an `IGNORED_REPOS` environment variable
* Wrap the handlers to check against that list before fetching the diff
* Always exclude `*.min.*` files
* Don't work with titles over 256 characters. GitHub wouldn't accept them anyway.

Performance guards

---

lib/push-handler.js
lib/utils/check-for-duplicate-issue.js
lib/utils/generate-label.js
lib/utils/main-loop.js
tests/fixtures/diffs/duplicate.txt
tests/helpers.js
tests/lib/check-for-duplicate-issue.test.js
tests/push-handler.test.js

#192 surfaced some more realistic response time metrics, and operations can be pretty slow, especially for large diffs or PRs that change a lot of files. This PR paralellizes some requests using `Promise.all`. There is a case where one TODO can be duplicated in the same diff - I've added a test for that case and used `context.todos = []` to track issues generated in the same run.

Performance improvements

---

lib/utils/get-diff.js
lib/utils/main-loop.js
tests/helpers.js
tests/lib/main-loop.test.js
tests/pull-request-handler.test.js
tests/pull-request-merge-handler.test.js
tests/push-handler.test.js

I believe this to be the root cause of #189 ! Large diffs were taking down the app. I noticed one in particular that was 4mb large - that was causing issues. Upon some digging, that diff turned out to be the addition of one huge file called `vendor.js` - we really don't need to be scanning files like that, or minified files in general.
~As a temporary measure, I've made it check the length of the diff against a max size of 1,000,000 characters.~
~It'd be great to do a timeout on the request itself, so if the payload is gigantic it'll just timeout. This above method still tries to download the whole payload which could be too large. I'm not sure if that's a built-in thing - @gr2m :wave: any ideas?~
I got some wonderful guidance from GitHub's API team who suggested a `HEAD` request to get …

Ignore big diffs

---

README.md

There's been some confusion around the need for a config file - it's totally optional, and in most cases, not needed. This PR adds some clarity to the Configuration section of the README.

Clarify optional config in README

---

.github/workflows/ci.yml

I noticed that CI isn't triggering for PRs from forks, because the Actions workflow is set to only trigger on `push`.

Trigger CI for PRs

---

bin/todo.js

This addressed the following warning:
```
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
at RequestError.get (/Users/jonasbn/develop/github-forks/todo/node_modules/@octokit/request-error/dist-node/index.js:29:17)
at /Users/jonasbn/develop/github-forks/todo/bin/todo.js:84:11 {
name: 'Deprecation'
```

Eliminated warning
